plugins:
  whos_online_enabled:
    default: true
    client: true
  whos_online_active_timeago:
    default: 5
    client: true
  whos_online_collapse_threshold:
    default: 10
    client: true
  whos_online_maximum_display:
    default: 50
    client: true
  whos_online_minimum_display:
    default: 1
    client: true
  whos_online_hide_below_minimum_display:
    default: false
    client: true
  whos_online_display_public:
    default: true
    client: true
  whos_online_display_min_trust_level:
    default: 0
    enum: 'TrustLevelSetting'
    client: true
  whos_online_avatar_indicator:
    default: 'glow'
    type: enum
    client: true
    choices:
      - glow
      - flair
      - none